import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../components/Layout/Navbar'
import Hero from '../components/Hero/Hero'
import Products from '../components/Products'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link
          href='https://fonts.cdnfonts.com/css/gilroy-bold'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        <Hero />
        <Products />
      </main>
    </>
  )
}
